import { describe, expect, it } from "vitest";

import type { TeamSeasonStat } from "@/lib/domain/kbo/types";
import type { TrainingCorpusSeason } from "@/lib/data-sources/kbo/training-corpus-types";
import {
  buildPregameEloDiffByGameId,
  buildPregameEloDiffBySampleId,
} from "@/lib/sim/kbo/direct-game/elo";

describe("direct game elo", () => {
  it("builds pregame elo diffs for training samples without looking ahead", () => {
    const season: TrainingCorpusSeason = {
      generatedAt: "2026-04-17T00:00:00.000Z",
      seasonId: "kbo-2025",
      year: 2025,
      teamExampleCount: 0,
      gameExampleCount: 2,
      teamExamples: [],
      gameExamples: [
        {
          sampleId: "g1",
          seasonId: "kbo-2025",
          year: 2025,
          gameKey: "g1",
          date: "2025-03-23",
          scheduledAt: "2025-03-23T14:00:00+09:00",
          month: 3,
          homeFranchiseId: "home",
          awayFranchiseId: "away",
          homeBrandLabel: "Home",
          awayBrandLabel: "Away",
          homeRank: 1,
          awayRank: 2,
          rankGap: 1,
          homePct: 0.5,
          awayPct: 0.5,
          pctGap: 0,
          homeGamesBack: 0,
          awayGamesBack: 0,
          gamesBackGap: 0,
          homeRecent10WinRate: 0.5,
          awayRecent10WinRate: 0.5,
          recent10Gap: 0,
          homeRecent10OpponentAvgPriorPct: 0.5,
          awayRecent10OpponentAvgPriorPct: 0.5,
          recent10OpponentPriorGap: 0,
          homeOpponentAdjustedRecent10WinRate: 0.5,
          awayOpponentAdjustedRecent10WinRate: 0.5,
          opponentAdjustedRecent10Gap: 0,
          homeRunsScoredPerGame: 4,
          awayRunsScoredPerGame: 4,
          offenseGap: 0,
          homeRunsAllowedPerGame: 4,
          awayRunsAllowedPerGame: 4,
          defenseGap: 0,
          homeRunDiffPerGame: 0,
          awayRunDiffPerGame: 0,
          runDiffGap: 0,
          homeHomePct: 0.5,
          awayAwayPct: 0.5,
          venueSplitGap: 0,
          homeSeasonProgress: 0.01,
          awaySeasonProgress: 0.01,
          progressGap: 0,
          homeDerivedCurrentWeight: 0.05,
          awayDerivedCurrentWeight: 0.05,
          currentWeightGap: 0,
          homeDerivedOffenseRating: 100,
          awayDerivedOffenseRating: 100,
          offenseRatingGap: 0,
          homeDerivedStarterRating: 100,
          awayDerivedStarterRating: 100,
          starterRatingGap: 0,
          homeDerivedBullpenRating: 100,
          awayDerivedBullpenRating: 100,
          bullpenRatingGap: 0,
          homeDerivedConfidenceScore: 0.2,
          awayDerivedConfidenceScore: 0.2,
          confidenceScoreGap: 0,
          homeDerivedRecentFormAdjustment: 0,
          awayDerivedRecentFormAdjustment: 0,
          recentFormAdjustmentGap: 0,
          homeDerivedScheduleDifficulty: 0,
          awayDerivedScheduleDifficulty: 0,
          scheduleDifficultyGap: 0,
          homeDerivedHomeFieldAdjustment: 0,
          homeRestDays: 0,
          awayRestDays: 0,
          restGap: 0,
          outcome: "homeWin",
          homeWin: true,
          awayWin: false,
          tie: false,
          homeScore: 5,
          awayScore: 3,
        },
        {
          sampleId: "g2",
          seasonId: "kbo-2025",
          year: 2025,
          gameKey: "g2",
          date: "2025-03-25",
          scheduledAt: "2025-03-25T18:30:00+09:00",
          month: 3,
          homeFranchiseId: "home",
          awayFranchiseId: "away",
          homeBrandLabel: "Home",
          awayBrandLabel: "Away",
          homeRank: 1,
          awayRank: 2,
          rankGap: 1,
          homePct: 1,
          awayPct: 0,
          pctGap: 1,
          homeGamesBack: 0,
          awayGamesBack: 1,
          gamesBackGap: 1,
          homeRecent10WinRate: 1,
          awayRecent10WinRate: 0,
          recent10Gap: 1,
          homeRecent10OpponentAvgPriorPct: 0.5,
          awayRecent10OpponentAvgPriorPct: 0.5,
          recent10OpponentPriorGap: 0,
          homeOpponentAdjustedRecent10WinRate: 1,
          awayOpponentAdjustedRecent10WinRate: 0,
          opponentAdjustedRecent10Gap: 1,
          homeRunsScoredPerGame: 5,
          awayRunsScoredPerGame: 3,
          offenseGap: 2,
          homeRunsAllowedPerGame: 3,
          awayRunsAllowedPerGame: 5,
          defenseGap: -2,
          homeRunDiffPerGame: 2,
          awayRunDiffPerGame: -2,
          runDiffGap: 4,
          homeHomePct: 1,
          awayAwayPct: 0,
          venueSplitGap: 1,
          homeSeasonProgress: 0.02,
          awaySeasonProgress: 0.02,
          progressGap: 0,
          homeDerivedCurrentWeight: 0.08,
          awayDerivedCurrentWeight: 0.08,
          currentWeightGap: 0,
          homeDerivedOffenseRating: 101,
          awayDerivedOffenseRating: 99,
          offenseRatingGap: 2,
          homeDerivedStarterRating: 101,
          awayDerivedStarterRating: 99,
          starterRatingGap: 2,
          homeDerivedBullpenRating: 101,
          awayDerivedBullpenRating: 99,
          bullpenRatingGap: 2,
          homeDerivedConfidenceScore: 0.25,
          awayDerivedConfidenceScore: 0.25,
          confidenceScoreGap: 0,
          homeDerivedRecentFormAdjustment: 0.1,
          awayDerivedRecentFormAdjustment: -0.1,
          recentFormAdjustmentGap: 0.2,
          homeDerivedScheduleDifficulty: 0,
          awayDerivedScheduleDifficulty: 0,
          scheduleDifficultyGap: 0,
          homeDerivedHomeFieldAdjustment: 0,
          homeRestDays: 1,
          awayRestDays: 1,
          restGap: 0,
          outcome: "awayWin",
          homeWin: false,
          awayWin: true,
          tie: false,
          homeScore: 2,
          awayScore: 4,
        },
      ],
    };

    const diffBySampleId = buildPregameEloDiffBySampleId([season]);

    expect(diffBySampleId.g1).toBe(0);
    expect(diffBySampleId.g2).toBeGreaterThan(0);
  });

  it("seeds runtime elo from previous season stats", () => {
    const previousSeasonStats: TeamSeasonStat[] = [
      {
        seasonId: "kbo-2025",
        seasonTeamId: "kbo-2025:home",
        wins: 90,
        losses: 54,
        ties: 0,
        runsScored: 0,
        runsAllowed: 0,
        homeWins: 45,
        homeLosses: 27,
        awayWins: 45,
        awayLosses: 27,
        last10: "7-3",
        streak: "W2",
        offensePlus: 100,
        pitchingPlus: 100,
        bullpenEra: 4,
        teamWar: 0,
      },
      {
        seasonId: "kbo-2025",
        seasonTeamId: "kbo-2025:away",
        wins: 54,
        losses: 90,
        ties: 0,
        runsScored: 0,
        runsAllowed: 0,
        homeWins: 27,
        homeLosses: 45,
        awayWins: 27,
        awayLosses: 45,
        last10: "3-7",
        streak: "L2",
        offensePlus: 100,
        pitchingPlus: 100,
        bullpenEra: 4,
        teamWar: 0,
      },
    ];

    const diffByGameId = buildPregameEloDiffByGameId({
      games: [
        {
          gameId: "g1",
          scheduledAt: "2026-03-22T14:00:00+09:00",
          homeSeasonTeamId: "kbo-2026:home",
          awaySeasonTeamId: "kbo-2026:away",
          status: "scheduled",
          homeScore: null,
          awayScore: null,
          isTie: false,
        },
      ],
      previousSeasonStats,
    });

    expect(diffByGameId.g1).toBeGreaterThan(0);
  });
});
