import { describe, expect, it } from "vitest";

import type {
  Game,
  Player,
  PlayerGameStat,
  PlayerSeasonStat,
  RosterEvent,
  SeasonTeam,
  TeamSeasonStat,
} from "@/lib/domain/kbo/types";
import { buildPlayerImpactContext } from "@/lib/sim/kbo/player-impact";

describe("buildPlayerImpactContext", () => {
  const seasonTeams: SeasonTeam[] = [
    {
      seasonTeamId: "season:a",
      seasonId: "kbo-2026",
      franchiseId: "a",
      brandId: "a",
      venueId: "venue-a",
      managerNameKo: "감독A",
      preseasonPriors: {
        offenseRating: 100,
        starterRating: 100,
        bullpenRating: 100,
      },
      manualAdjustments: [],
      preseasonOutlook: "A",
    },
    {
      seasonTeamId: "season:b",
      seasonId: "kbo-2026",
      franchiseId: "b",
      brandId: "b",
      venueId: "venue-b",
      managerNameKo: "감독B",
      preseasonPriors: {
        offenseRating: 100,
        starterRating: 100,
        bullpenRating: 100,
      },
      manualAdjustments: [],
      preseasonOutlook: "B",
    },
  ];

  const games: Game[] = [
    {
      gameId: "past-a-1",
      seasonId: "kbo-2026",
      seriesId: "series-past-a",
      homeSeasonTeamId: "season:a",
      awaySeasonTeamId: "season:b",
      scheduledAt: "2026-04-13T18:30:00+09:00",
      status: "final",
      originalScheduledAt: null,
      rescheduledFromGameId: null,
      homeScore: 4,
      awayScore: 3,
      innings: 11,
      isTie: false,
      note: null,
      attendance: null,
      externalLinks: [],
    },
    {
      gameId: "past-b-1",
      seasonId: "kbo-2026",
      seriesId: "series-past-b",
      homeSeasonTeamId: "season:b",
      awaySeasonTeamId: "season:a",
      scheduledAt: "2026-04-12T18:30:00+09:00",
      status: "final",
      originalScheduledAt: null,
      rescheduledFromGameId: null,
      homeScore: 2,
      awayScore: 1,
      innings: 10,
      isTie: false,
      note: null,
      attendance: null,
      externalLinks: [],
    },
    {
      gameId: "past-b-2",
      seasonId: "kbo-2026",
      seriesId: "series-past-b",
      homeSeasonTeamId: "season:b",
      awaySeasonTeamId: "season:a",
      scheduledAt: "2026-04-13T18:30:00+09:00",
      status: "final",
      originalScheduledAt: null,
      rescheduledFromGameId: null,
      homeScore: 5,
      awayScore: 4,
      innings: 9,
      isTie: false,
      note: null,
      attendance: null,
      externalLinks: [],
    },
    {
      gameId: "game-1",
      seasonId: "kbo-2026",
      seriesId: "series-1",
      homeSeasonTeamId: "season:a",
      awaySeasonTeamId: "season:b",
      scheduledAt: "2026-04-17T18:30:00+09:00",
      status: "scheduled",
      originalScheduledAt: null,
      rescheduledFromGameId: null,
      homeScore: null,
      awayScore: null,
      innings: null,
      isTie: false,
      note: null,
      attendance: null,
      externalLinks: [],
    },
    {
      gameId: "game-2",
      seasonId: "kbo-2026",
      seriesId: "series-1",
      homeSeasonTeamId: "season:a",
      awaySeasonTeamId: "season:b",
      scheduledAt: "2026-04-18T18:30:00+09:00",
      status: "scheduled",
      originalScheduledAt: null,
      rescheduledFromGameId: null,
      homeScore: null,
      awayScore: null,
      innings: null,
      isTie: false,
      note: null,
      attendance: null,
      externalLinks: [],
    },
    {
      gameId: "game-3",
      seasonId: "kbo-2026",
      seriesId: "series-1",
      homeSeasonTeamId: "season:a",
      awaySeasonTeamId: "season:b",
      scheduledAt: "2026-04-19T18:30:00+09:00",
      status: "scheduled",
      originalScheduledAt: null,
      rescheduledFromGameId: null,
      homeScore: null,
      awayScore: null,
      innings: null,
      isTie: false,
      note: null,
      attendance: null,
      externalLinks: [],
    },
  ];

  const teamSeasonStats: TeamSeasonStat[] = [
    {
      seasonId: "kbo-2026",
      seasonTeamId: "season:a",
      wins: 12,
      losses: 8,
      ties: 0,
      runsScored: 98,
      runsAllowed: 84,
      homeWins: 6,
      homeLosses: 4,
      awayWins: 6,
      awayLosses: 4,
      last10: "6-4-0",
      streak: "W2",
      offensePlus: 104,
      pitchingPlus: 101,
      bullpenEra: 3.9,
      teamWar: 1.5,
    },
    {
      seasonId: "kbo-2026",
      seasonTeamId: "season:b",
      wins: 10,
      losses: 10,
      ties: 0,
      runsScored: 91,
      runsAllowed: 91,
      homeWins: 5,
      homeLosses: 5,
      awayWins: 5,
      awayLosses: 5,
      last10: "5-5-0",
      streak: "L1",
      offensePlus: 100,
      pitchingPlus: 100,
      bullpenEra: 4,
      teamWar: 1,
    },
  ];

  const players: Player[] = [
    {
      playerId: "a-h",
      slug: "a-h",
      nameKo: "A 타자",
      nameEn: "A hitter",
      birthDate: null,
      batsThrows: null,
      heightWeight: null,
      careerHistory: null,
      draftInfo: null,
      joinInfo: null,
      primaryPositions: ["OF"],
      debutYear: 2024,
      franchiseIds: ["a"],
      bio: "",
    },
    {
      playerId: "a-sp",
      slug: "a-sp",
      nameKo: "A 선발",
      nameEn: "A starter",
      birthDate: null,
      batsThrows: null,
      heightWeight: null,
      careerHistory: null,
      draftInfo: null,
      joinInfo: null,
      primaryPositions: ["SP"],
      debutYear: 2023,
      franchiseIds: ["a"],
      bio: "",
    },
    {
      playerId: "b-h",
      slug: "b-h",
      nameKo: "B 타자",
      nameEn: "B hitter",
      birthDate: null,
      batsThrows: null,
      heightWeight: null,
      careerHistory: null,
      draftInfo: null,
      joinInfo: null,
      primaryPositions: ["OF"],
      debutYear: 2024,
      franchiseIds: ["b"],
      bio: "",
    },
    {
      playerId: "b-sp",
      slug: "b-sp",
      nameKo: "B 선발",
      nameEn: "B starter",
      birthDate: null,
      batsThrows: null,
      heightWeight: null,
      careerHistory: null,
      draftInfo: null,
      joinInfo: null,
      primaryPositions: ["SP"],
      debutYear: 2023,
      franchiseIds: ["b"],
      bio: "",
    },
    {
      playerId: "b-sp-2",
      slug: "b-sp-2",
      nameKo: "B 2선발",
      nameEn: "B starter 2",
      birthDate: null,
      batsThrows: null,
      heightWeight: null,
      careerHistory: null,
      draftInfo: null,
      joinInfo: null,
      primaryPositions: ["SP"],
      debutYear: 2022,
      franchiseIds: ["b"],
      bio: "",
    },
    {
      playerId: "b-rp",
      slug: "b-rp",
      nameKo: "B 불펜",
      nameEn: "B reliever",
      birthDate: null,
      batsThrows: null,
      heightWeight: null,
      careerHistory: null,
      draftInfo: null,
      joinInfo: null,
      primaryPositions: ["RP"],
      debutYear: 2023,
      franchiseIds: ["b"],
      bio: "",
    },
  ];

  const playerSeasonStats: PlayerSeasonStat[] = [
    {
      statId: "a-h-2026",
      seasonId: "kbo-2026",
      playerId: "a-h",
      seasonTeamId: "season:a",
      statType: "hitter",
      games: 20,
      plateAppearances: 82,
      atBats: 71,
      hits: 24,
      homeRuns: 4,
      ops: 0.79,
      era: null,
      inningsPitched: null,
      strikeouts: null,
      saves: null,
      wins: null,
      losses: null,
      war: 0.9,
    },
    {
      statId: "a-sp-2026",
      seasonId: "kbo-2026",
      playerId: "a-sp",
      seasonTeamId: "season:a",
      statType: "pitcher",
      games: 4,
      plateAppearances: null,
      atBats: null,
      hits: null,
      homeRuns: null,
      ops: null,
      era: 3.05,
      inningsPitched: 27,
      strikeouts: 30,
      saves: 0,
      wins: 2,
      losses: 1,
      war: 0.9,
    },
    {
      statId: "b-h-2026",
      seasonId: "kbo-2026",
      playerId: "b-h",
      seasonTeamId: "season:b",
      statType: "hitter",
      games: 18,
      plateAppearances: 74,
      atBats: 64,
      hits: 24,
      homeRuns: 4,
      ops: 0.82,
      era: null,
      inningsPitched: null,
      strikeouts: null,
      saves: null,
      wins: null,
      losses: null,
      war: 0.9,
    },
    {
      statId: "b-sp-2026",
      seasonId: "kbo-2026",
      playerId: "b-sp",
      seasonTeamId: "season:b",
      statType: "pitcher",
      games: 4,
      plateAppearances: null,
      atBats: null,
      hits: null,
      homeRuns: null,
      ops: null,
      era: 3.35,
      inningsPitched: 25,
      strikeouts: 23,
      saves: 0,
      wins: 2,
      losses: 1,
      war: 0.6,
    },
    {
      statId: "b-sp-2-2026",
      seasonId: "kbo-2026",
      playerId: "b-sp-2",
      seasonTeamId: "season:b",
      statType: "pitcher",
      games: 4,
      plateAppearances: null,
      atBats: null,
      hits: null,
      homeRuns: null,
      ops: null,
      era: 3.55,
      inningsPitched: 24,
      strikeouts: 20,
      saves: 0,
      wins: 1,
      losses: 1,
      war: 0.4,
    },
    {
      statId: "b-rp-2026",
      seasonId: "kbo-2026",
      playerId: "b-rp",
      seasonTeamId: "season:b",
      statType: "pitcher",
      games: 8,
      plateAppearances: null,
      atBats: null,
      hits: null,
      homeRuns: null,
      ops: null,
      era: 3.1,
      inningsPitched: 9,
      strikeouts: 12,
      saves: 2,
      wins: 0,
      losses: 0,
      war: 0.3,
    },
  ];

  const playerGameStats: PlayerGameStat[] = [
    {
      playerGameStatId: "past-a-1:a-sp",
      gameId: "past-a-1",
      seasonId: "kbo-2026",
      playerId: "a-sp",
      seasonTeamId: "season:a",
      statType: "pitcher",
      summaryLine: "6이닝 2실점 7K",
    },
    {
      playerGameStatId: "past-b-1:b-sp",
      gameId: "past-b-1",
      seasonId: "kbo-2026",
      playerId: "b-sp",
      seasonTeamId: "season:b",
      statType: "pitcher",
      summaryLine: "6이닝 1실점 6K",
    },
    {
      playerGameStatId: "past-b-2:b-sp-2",
      gameId: "past-b-2",
      seasonId: "kbo-2026",
      playerId: "b-sp-2",
      seasonTeamId: "season:b",
      statType: "pitcher",
      summaryLine: "5이닝 2실점 4K",
    },
    {
      playerGameStatId: "past-b-1:b-rp",
      gameId: "past-b-1",
      seasonId: "kbo-2026",
      playerId: "b-rp",
      seasonTeamId: "season:b",
      statType: "pitcher",
      summaryLine: "2이닝 무실점 3K",
    },
    {
      playerGameStatId: "past-b-2:b-rp",
      gameId: "past-b-2",
      seasonId: "kbo-2026",
      playerId: "b-rp",
      seasonTeamId: "season:b",
      statType: "pitcher",
      summaryLine: "1.1이닝 1실점 2K",
    },
  ];

  const rosterEvents: RosterEvent[] = [
    {
      rosterEventId: "a-sp-injured",
      seasonId: "kbo-2026",
      playerId: "a-sp",
      seasonTeamId: "season:a",
      type: "injured",
      date: "2026-04-15",
      note: "어깨 피로로 등판 간격 조정",
    },
    {
      rosterEventId: "b-h-activated",
      seasonId: "kbo-2026",
      playerId: "b-h",
      seasonTeamId: "season:b",
      type: "activated",
      date: "2026-04-14",
      note: "선발 복귀",
    },
  ];

  it("reflects roster availability and projects likely starter turns", () => {
    const context = buildPlayerImpactContext({
      seasonTeams,
      games,
      teamSeasonStats,
      players,
      rosterEvents,
      playerSeasonStats,
      playerGameStats,
    });

    expect(context.byTeamId["season:a"]?.starterDelta).toBeLessThan(0);
    expect(context.byTeamId["season:b"]?.offenseDelta).toBeGreaterThan(0);
    expect(context.starterByGameId["game-1"]?.home).toBeNull();
    expect(context.starterByGameId["game-1"]?.away?.playerId).toBe("b-sp");
    expect(context.starterByGameId["game-2"]?.away?.playerId).toBe("b-sp-2");
    expect(context.starterByGameId["game-3"]?.away).toBeNull();
    expect(context.starterByGameId["game-3"]?.home?.playerId).toBe("a-sp");
    expect(
      context.byTeamId["season:b"]?.explanationReasons.some((reason) =>
        reason.key.startsWith("bullpen-load:"),
      ),
    ).toBe(true);
    expect(context.byTeamId["season:a"]?.explanationReasons.length).toBeGreaterThan(0);
  });
});
