import { describe, expect, it } from "vitest";

import type { Game, Player, PlayerSeasonStat, TeamDisplay, TeamSeasonStat, TeamSplitStat } from "@/lib/domain/kbo/types";
import {
  buildGameLogRows,
  buildHitterLeaderRows,
  buildPitcherLeaderRows,
  buildPlayerSituationGroupOptions,
  buildPlayerSituationValueOptions,
  buildPlayerSplitLeaderRows,
  buildSplitExplorerRows,
  buildTeamRecordRows,
  PLAYER_RECORD_FILTER_ALL,
} from "@/lib/records/kbo-records";

const displayById: Record<string, TeamDisplay> = {
  "season:lg": {
    seasonTeamId: "season:lg",
    brandId: "lg",
    franchiseId: "lg",
    teamSlug: "lg-twins",
    displayNameKo: "LG 트윈스",
    shortNameKo: "LG",
    shortCode: "LG",
    primaryColor: "#a50034",
    secondaryColor: "#111111",
  },
  "season:kia": {
    seasonTeamId: "season:kia",
    brandId: "kia",
    franchiseId: "kia",
    teamSlug: "kia-tigers",
    displayNameKo: "KIA 타이거즈",
    shortNameKo: "KIA",
    shortCode: "KIA",
    primaryColor: "#ea0029",
    secondaryColor: "#111111",
  },
};

describe("records helpers", () => {
  it("sorts team records by selected metric", () => {
    const rows: TeamSeasonStat[] = [
      {
        seasonId: "season",
        seasonTeamId: "season:lg",
        wins: 12,
        losses: 8,
        ties: 0,
        runsScored: 90,
        runsAllowed: 80,
        homeWins: 6,
        homeLosses: 4,
        awayWins: 6,
        awayLosses: 4,
        last10: "6-4",
        streak: "승1",
        offensePlus: 110,
        pitchingPlus: 101,
        bullpenEra: 3.8,
        teamWar: 12.2,
      },
      {
        seasonId: "season",
        seasonTeamId: "season:kia",
        wins: 11,
        losses: 9,
        ties: 0,
        runsScored: 88,
        runsAllowed: 76,
        homeWins: 5,
        homeLosses: 5,
        awayWins: 6,
        awayLosses: 4,
        last10: "5-5",
        streak: "패1",
        offensePlus: 106,
        pitchingPlus: 108,
        bullpenEra: 3.5,
        teamWar: 12.9,
      },
    ];

    expect(buildTeamRecordRows(rows, displayById, "wins", "")[0]?.seasonTeamId).toBe("season:lg");
    expect(buildTeamRecordRows(rows, displayById, "runsAllowed", "")[0]?.seasonTeamId).toBe("season:kia");
    expect(buildTeamRecordRows(rows, displayById, "runDiff", "")[0]?.seasonTeamId).toBe("season:kia");
  });

  it("builds hitter, pitcher, split, and game rows with filtering", () => {
    const players: Player[] = [
      {
        playerId: "p1",
        slug: "p1",
        nameKo: "김타자",
        nameEn: "Kim",
        birthDate: null,
        batsThrows: null,
        heightWeight: null,
        careerHistory: null,
        draftInfo: null,
        joinInfo: null,
        primaryPositions: ["OF"],
        debutYear: 2020,
        franchiseIds: ["lg"],
        bio: "",
      },
      {
        playerId: "p2",
        slug: "p2",
        nameKo: "박투수",
        nameEn: "Park",
        birthDate: null,
        batsThrows: null,
        heightWeight: null,
        careerHistory: null,
        draftInfo: null,
        joinInfo: null,
        primaryPositions: ["SP"],
        debutYear: 2020,
        franchiseIds: ["kia"],
        bio: "",
      },
    ];
    const stats: PlayerSeasonStat[] = [
      {
        statId: "h1",
        seasonId: "season",
        playerId: "p1",
        seasonTeamId: "season:lg",
        statType: "hitter",
        games: 20,
        plateAppearances: 80,
        atBats: 70,
        hits: 25,
        homeRuns: 6,
        ops: 0.945,
        era: null,
        inningsPitched: null,
        strikeouts: null,
        saves: null,
        wins: null,
        losses: null,
        war: 1.8,
      },
      {
        statId: "p1",
        seasonId: "season",
        playerId: "p2",
        seasonTeamId: "season:kia",
        statType: "pitcher",
        games: 5,
        plateAppearances: null,
        atBats: null,
        hits: null,
        homeRuns: null,
        ops: null,
        era: 2.33,
        inningsPitched: 27,
        strikeouts: 31,
        saves: 0,
        wins: 3,
        losses: 1,
        war: 1.6,
      },
    ];
    const splits: TeamSplitStat[] = [
      {
        splitId: "s1",
        seasonId: "season",
        seasonTeamId: "season:lg",
        splitType: "home",
        wins: 6,
        losses: 4,
        ties: 0,
        metricLabel: "홈",
        metricValue: "6-4 / .600",
      },
    ];
    const games: Game[] = [
      {
        gameId: "g1",
        seasonId: "season",
        seriesId: "series-1",
        homeSeasonTeamId: "season:lg",
        awaySeasonTeamId: "season:kia",
        scheduledAt: "2026-04-15T09:30:00.000Z",
        status: "final",
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: 5,
        awayScore: 3,
        innings: 9,
        isTie: false,
        note: null,
        attendance: 15000,
        externalLinks: [],
      },
    ];
    const filters = {
      query: "김",
      seasonTeamId: PLAYER_RECORD_FILTER_ALL,
      position: PLAYER_RECORD_FILTER_ALL,
    };

    expect(buildHitterLeaderRows(stats, players, displayById, "ops", filters)[0]?.playerId).toBe("p1");
    expect(
      buildPitcherLeaderRows(stats, players, displayById, "era", {
        ...filters,
        query: "박",
      })[0]?.playerId,
    ).toBe("p2");
    expect(buildSplitExplorerRows(splits, displayById, "home", "LG")).toHaveLength(1);
    expect(buildGameLogRows(games, displayById, "KIA", true)).toHaveLength(1);
  });

  it("pushes zero and missing values behind ranked players", () => {
    const players: Player[] = [
      {
        playerId: "p1",
        slug: "p1",
        nameKo: "정상투수",
        nameEn: "A",
        birthDate: null,
        batsThrows: null,
        heightWeight: null,
        careerHistory: null,
        draftInfo: null,
        joinInfo: null,
        primaryPositions: ["P"],
        debutYear: 2020,
        franchiseIds: ["lg"],
        bio: "",
      },
      {
        playerId: "p2",
        slug: "p2",
        nameKo: "무실점투수",
        nameEn: "B",
        birthDate: null,
        batsThrows: null,
        heightWeight: null,
        careerHistory: null,
        draftInfo: null,
        joinInfo: null,
        primaryPositions: ["P"],
        debutYear: 2020,
        franchiseIds: ["kia"],
        bio: "",
      },
      {
        playerId: "p3",
        slug: "p3",
        nameKo: "기록없음투수",
        nameEn: "C",
        birthDate: null,
        batsThrows: null,
        heightWeight: null,
        careerHistory: null,
        draftInfo: null,
        joinInfo: null,
        primaryPositions: ["P"],
        debutYear: 2020,
        franchiseIds: ["kia"],
        bio: "",
      },
    ];
    const stats: PlayerSeasonStat[] = [
      {
        statId: "p1",
        seasonId: "season",
        playerId: "p1",
        seasonTeamId: "season:lg",
        statType: "pitcher",
        games: 5,
        plateAppearances: null,
        atBats: null,
        hits: null,
        homeRuns: null,
        ops: null,
        era: 2.33,
        inningsPitched: 27,
        strikeouts: 31,
        saves: 0,
        wins: 3,
        losses: 1,
        war: 1.6,
      },
      {
        statId: "p2",
        seasonId: "season",
        playerId: "p2",
        seasonTeamId: "season:kia",
        statType: "pitcher",
        games: 2,
        plateAppearances: null,
        atBats: null,
        hits: null,
        homeRuns: null,
        ops: null,
        era: 0,
        inningsPitched: 2,
        strikeouts: 1,
        saves: 0,
        wins: 0,
        losses: 0,
        war: 0,
      },
      {
        statId: "p3",
        seasonId: "season",
        playerId: "p3",
        seasonTeamId: "season:kia",
        statType: "pitcher",
        games: 0,
        plateAppearances: null,
        atBats: null,
        hits: null,
        homeRuns: null,
        ops: null,
        era: null,
        inningsPitched: null,
        strikeouts: null,
        saves: null,
        wins: null,
        losses: null,
        war: 0,
      },
    ];

    const rows = buildPitcherLeaderRows(stats, players, displayById, "era", {
      query: "",
      seasonTeamId: PLAYER_RECORD_FILTER_ALL,
      position: PLAYER_RECORD_FILTER_ALL,
    });

    expect(rows.map((row) => row.playerId)).toEqual(["p1", "p2", "p3"]);
    expect(rows[2]?.primaryLabel).toBe("ERA 기록 없음");
  });

  it("builds player split filters and split leaderboard rows", () => {
    const players: Player[] = [
      {
        playerId: "p1",
        slug: "p1",
        nameKo: "김타자",
        nameEn: "Kim",
        birthDate: null,
        batsThrows: null,
        heightWeight: null,
        careerHistory: null,
        draftInfo: null,
        joinInfo: null,
        primaryPositions: ["OF"],
        debutYear: 2020,
        franchiseIds: ["lg"],
        bio: "",
      },
      {
        playerId: "p2",
        slug: "p2",
        nameKo: "이타자",
        nameEn: "Lee",
        birthDate: null,
        batsThrows: null,
        heightWeight: null,
        careerHistory: null,
        draftInfo: null,
        joinInfo: null,
        primaryPositions: ["C"],
        debutYear: 2021,
        franchiseIds: ["kia"],
        bio: "",
      },
    ];
    const splitStats = [
      {
        playerSplitStatId: "ps1",
        seasonId: "season",
        playerId: "p1",
        seasonTeamId: "season:lg",
        statType: "hitter" as const,
        splitType: "month" as const,
        splitKey: "APR",
        splitLabel: "4월",
        games: 8,
        plateAppearances: 30,
        battingAverage: 0.4,
        atBats: 25,
        runs: 6,
        hits: 10,
        homeRuns: 2,
        rbi: 7,
        stolenBases: 3,
        walks: 4,
        ops: null,
        era: null,
        inningsPitched: null,
        strikeouts: 5,
        saves: null,
        wins: null,
        losses: null,
        holds: null,
        hitsAllowed: null,
        homeRunsAllowed: null,
        runsAllowed: null,
        earnedRuns: null,
        opponentAvg: null,
        summaryLine: "4월 .400 · 10안타 · 2홈런 · 7타점",
      },
      {
        playerSplitStatId: "ps2",
        seasonId: "season",
        playerId: "p2",
        seasonTeamId: "season:kia",
        statType: "hitter" as const,
        splitType: "situation" as const,
        splitKey: "VS LEFTY",
        splitLabel: "좌투 상대",
        games: 0,
        plateAppearances: 18,
        battingAverage: 0.333,
        atBats: 15,
        runs: null,
        hits: 5,
        homeRuns: 1,
        rbi: 4,
        stolenBases: null,
        walks: 2,
        ops: null,
        era: null,
        inningsPitched: null,
        strikeouts: 3,
        saves: null,
        wins: null,
        losses: null,
        holds: null,
        hitsAllowed: null,
        homeRunsAllowed: null,
        runsAllowed: null,
        earnedRuns: null,
        opponentAvg: null,
        summaryLine: "좌투 상대 .333 · 5안타 · 1홈런 · 4타점",
      },
    ];

    expect(buildPlayerSituationGroupOptions(splitStats, "hitter", "battingAverage")).toEqual([
      { value: "all", label: "경기상황별1" },
      { value: "month", label: "월별" },
      { value: "matchup", label: "상대 유형" },
    ]);

    expect(
      buildPlayerSituationValueOptions(
        splitStats,
        players,
        "hitter",
        "battingAverage",
        "month",
        PLAYER_RECORD_FILTER_ALL,
        PLAYER_RECORD_FILTER_ALL,
      ),
    ).toEqual([
      { value: "all", label: "경기상황별2" },
      { value: "APR", label: "4월" },
    ]);

    expect(
      buildPlayerSplitLeaderRows(
        splitStats,
        players,
        displayById,
        "hitter",
        "battingAverage",
        {
          query: "",
          seasonTeamId: "season:lg",
          position: "OF",
        },
        "month",
        "APR",
      )[0],
    ).toMatchObject({
      playerId: "p1",
      primaryLabel: "타율 .400",
    });
  });
});
