import { describe, expect, it } from "vitest";

import { simulateSeason } from "@/lib/sim/kbo";
import {
  buildScenarioQueryAnalysis,
  getScenarioTargetProbability,
} from "@/lib/sim/kbo";
import type {
  KboSeasonRuleset,
  Season,
  SeasonTeam,
  Series,
  TeamDisplay,
  TeamSeasonStat,
} from "@/lib/domain/kbo/types";

describe("scenario query helpers", () => {
  it("maps scenario targets to the expected probability bucket", () => {
    expect(
      getScenarioTargetProbability(
        "top2",
        {
          seasonTeamId: "season:lg",
          first: 0.21,
          second: 0.19,
          third: 0.18,
          fourth: 0.14,
          fifth: 0.11,
          missPostseason: 0.17,
        },
        {
          seasonTeamId: "season:lg",
          wildcard: 0.22,
          semipo: 0.18,
          po: 0.12,
          ks: 0.09,
          champion: 0.05,
        },
      ),
    ).toBeCloseTo(0.4);
    expect(
      getScenarioTargetProbability(
        "postseason",
        {
          seasonTeamId: "season:lg",
          first: 0.21,
          second: 0.19,
          third: 0.18,
          fourth: 0.14,
          fifth: 0.11,
          missPostseason: 0.17,
        },
        null,
      ),
    ).toBeCloseTo(0.83);
    expect(
      getScenarioTargetProbability(
        "champion",
        null,
        {
          seasonTeamId: "season:lg",
          wildcard: 0.22,
          semipo: 0.18,
          po: 0.12,
          ks: 0.09,
          champion: 0.05,
        },
      ),
    ).toBeCloseTo(0.05);
  });

  it("builds quick scenario analysis for the selected team's next series", () => {
    const season: Season = {
      seasonId: "season-2026",
      year: 2026,
      label: "2026 KBO",
      status: "ongoing",
      phase: "regular",
      rulesetId: "kbo-2026",
      openingDay: "2026-03-28",
      regularSeasonStart: "2026-03-28",
      regularSeasonEnd: "2026-09-20",
      postseasonStart: "2026-10-01",
      postseasonEnd: "2026-11-01",
      updatedAt: "2026-04-17T12:00:00+09:00",
    };
    const ruleset: KboSeasonRuleset = {
      rulesetId: "kbo-2026",
      label: "KBO 2026",
      regularSeasonGamesPerTeam: 144,
      gamesPerOpponent: 16,
      tiesAllowed: true,
      tiebreakerOrder: ["headToHead", "runDifferential", "runScored", "teamCode"],
      specialPlayoffGamePositions: [],
      postseasonFormat: [
        { round: "wildcard", label: "WC", bestOf: 3, higherSeedAdvantageWins: 1 },
        { round: "semipo", label: "Semi", bestOf: 5, higherSeedAdvantageWins: 0 },
        { round: "po", label: "PO", bestOf: 5, higherSeedAdvantageWins: 0 },
        { round: "ks", label: "KS", bestOf: 7, higherSeedAdvantageWins: 0 },
      ],
      notes: [],
    };
    const seasonTeams: SeasonTeam[] = [
      {
        seasonTeamId: "season:lg",
        seasonId: season.seasonId,
        franchiseId: "lg",
        brandId: "lg",
        venueId: "jamsil",
        managerNameKo: "감독 A",
        preseasonPriors: {
          offenseRating: 108,
          starterRating: 107,
          bullpenRating: 106,
        },
        manualAdjustments: [],
        preseasonOutlook: "상위권",
      },
      {
        seasonTeamId: "season:ssg",
        seasonId: season.seasonId,
        franchiseId: "ssg",
        brandId: "ssg",
        venueId: "incheon",
        managerNameKo: "감독 B",
        preseasonPriors: {
          offenseRating: 99,
          starterRating: 98,
          bullpenRating: 99,
        },
        manualAdjustments: [],
        preseasonOutlook: "중위권",
      },
      {
        seasonTeamId: "season:kia",
        seasonId: season.seasonId,
        franchiseId: "kia",
        brandId: "kia",
        venueId: "gwangju",
        managerNameKo: "감독 C",
        preseasonPriors: {
          offenseRating: 101,
          starterRating: 102,
          bullpenRating: 100,
        },
        manualAdjustments: [],
        preseasonOutlook: "상위권 경쟁",
      },
    ];
    const teamSeasonStats: TeamSeasonStat[] = [
      {
        seasonId: season.seasonId,
        seasonTeamId: "season:lg",
        wins: 8,
        losses: 8,
        ties: 0,
        runsScored: 78,
        runsAllowed: 74,
        homeWins: 4,
        homeLosses: 4,
        awayWins: 4,
        awayLosses: 4,
        last10: "5-5",
        streak: "W1",
        offensePlus: 103,
        pitchingPlus: 101,
        bullpenEra: 3.9,
        teamWar: 6.2,
      },
      {
        seasonId: season.seasonId,
        seasonTeamId: "season:ssg",
        wins: 8,
        losses: 8,
        ties: 0,
        runsScored: 70,
        runsAllowed: 75,
        homeWins: 4,
        homeLosses: 4,
        awayWins: 4,
        awayLosses: 4,
        last10: "5-5",
        streak: "L1",
        offensePlus: 100,
        pitchingPlus: 99,
        bullpenEra: 4.1,
        teamWar: 5.1,
      },
      {
        seasonId: season.seasonId,
        seasonTeamId: "season:kia",
        wins: 9,
        losses: 7,
        ties: 0,
        runsScored: 76,
        runsAllowed: 72,
        homeWins: 5,
        homeLosses: 3,
        awayWins: 4,
        awayLosses: 4,
        last10: "6-4",
        streak: "W2",
        offensePlus: 101,
        pitchingPlus: 102,
        bullpenEra: 3.8,
        teamWar: 6.0,
      },
    ];
    const series: Series[] = [
      {
        seriesId: "series-1",
        seasonId: season.seasonId,
        type: "regular",
        homeSeasonTeamId: "season:lg",
        awaySeasonTeamId: "season:ssg",
        plannedLength: 3,
        actualLength: 0,
        startDate: "2026-04-18",
        endDate: "2026-04-20",
        venueId: "jamsil",
        status: "scheduled",
      },
      {
        seriesId: "series-2",
        seasonId: season.seasonId,
        type: "regular",
        homeSeasonTeamId: "season:ssg",
        awaySeasonTeamId: "season:kia",
        plannedLength: 3,
        actualLength: 0,
        startDate: "2026-04-21",
        endDate: "2026-04-23",
        venueId: "incheon",
        status: "scheduled",
      },
    ];
    const games = [
      {
        gameId: "game-1",
        seasonId: season.seasonId,
        seriesId: "series-1",
        homeSeasonTeamId: "season:lg",
        awaySeasonTeamId: "season:ssg",
        scheduledAt: "2026-04-18T18:30:00+09:00",
        status: "scheduled" as const,
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: null,
        awayScore: null,
        innings: null,
        isTie: false,
        note: null,
        attendance: null,
        externalLinks: [],
      },
      {
        gameId: "game-2",
        seasonId: season.seasonId,
        seriesId: "series-1",
        homeSeasonTeamId: "season:lg",
        awaySeasonTeamId: "season:ssg",
        scheduledAt: "2026-04-19T14:00:00+09:00",
        status: "scheduled" as const,
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: null,
        awayScore: null,
        innings: null,
        isTie: false,
        note: null,
        attendance: null,
        externalLinks: [],
      },
      {
        gameId: "game-3",
        seasonId: season.seasonId,
        seriesId: "series-1",
        homeSeasonTeamId: "season:lg",
        awaySeasonTeamId: "season:ssg",
        scheduledAt: "2026-04-20T18:30:00+09:00",
        status: "scheduled" as const,
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: null,
        awayScore: null,
        innings: null,
        isTie: false,
        note: null,
        attendance: null,
        externalLinks: [],
      },
      {
        gameId: "game-4",
        seasonId: season.seasonId,
        seriesId: "series-2",
        homeSeasonTeamId: "season:ssg",
        awaySeasonTeamId: "season:kia",
        scheduledAt: "2026-04-21T18:30:00+09:00",
        status: "scheduled" as const,
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: null,
        awayScore: null,
        innings: null,
        isTie: false,
        note: null,
        attendance: null,
        externalLinks: [],
      },
      {
        gameId: "game-5",
        seasonId: season.seasonId,
        seriesId: "series-2",
        homeSeasonTeamId: "season:ssg",
        awaySeasonTeamId: "season:kia",
        scheduledAt: "2026-04-22T18:30:00+09:00",
        status: "scheduled" as const,
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: null,
        awayScore: null,
        innings: null,
        isTie: false,
        note: null,
        attendance: null,
        externalLinks: [],
      },
      {
        gameId: "game-6",
        seasonId: season.seasonId,
        seriesId: "series-2",
        homeSeasonTeamId: "season:ssg",
        awaySeasonTeamId: "season:kia",
        scheduledAt: "2026-04-23T18:30:00+09:00",
        status: "scheduled" as const,
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: null,
        awayScore: null,
        innings: null,
        isTie: false,
        note: null,
        attendance: null,
        externalLinks: [],
      },
    ];
    const displayById: Record<string, TeamDisplay> = {
      "season:lg": {
        seasonTeamId: "season:lg",
        franchiseId: "lg",
        brandId: "lg",
        teamSlug: "lg-twins",
        displayNameKo: "LG 트윈스",
        shortNameKo: "LG",
        shortCode: "LG",
        primaryColor: "#c4002b",
        secondaryColor: "#000000",
      },
      "season:ssg": {
        seasonTeamId: "season:ssg",
        franchiseId: "ssg",
        brandId: "ssg",
        teamSlug: "ssg-landers",
        displayNameKo: "SSG 랜더스",
        shortNameKo: "SSG",
        shortCode: "SSG",
        primaryColor: "#ce0e2d",
        secondaryColor: "#f5f5f5",
      },
      "season:kia": {
        seasonTeamId: "season:kia",
        franchiseId: "kia",
        brandId: "kia",
        teamSlug: "kia-tigers",
        displayNameKo: "KIA 타이거즈",
        shortNameKo: "KIA",
        shortCode: "KIA",
        primaryColor: "#ea0029",
        secondaryColor: "#06141f",
      },
    };

    const baseInput = {
      season,
      ruleset,
      seasonTeams,
      series,
      games,
      teamSeasonStats,
      players: [],
      rosterEvents: [],
      playerSeasonStats: [],
      playerGameStats: [],
      previousSeasonStats: [] satisfies TeamSeasonStat[],
    };
    const snapshot = simulateSeason(
      {
        ...baseInput,
        scenarioOverrides: [],
      },
      60,
    );

    const analysis = buildScenarioQueryAnalysis({
      baseInput,
      currentSnapshot: snapshot,
      scenarioOverrides: [],
      selectedTeamId: "season:lg",
      target: "first",
      displayById,
      iterations: 60,
    });

    expect(analysis.currentProbability).toBeGreaterThan(0);
    expect(analysis.nextSeries).not.toBeNull();
    expect(analysis.leverageSeries).toHaveLength(1);
    expect(analysis.rivalSeries.length).toBeGreaterThan(0);
    expect(analysis.requiredWins).not.toBeNull();
    expect(analysis.requiredWins?.thresholds).toHaveLength(3);
    expect(analysis.nextSeries?.favorable.probability).toBeGreaterThan(
      analysis.nextSeries?.unfavorable.probability ?? 0,
    );
  });
});
