import { describe, expect, it } from "vitest";

import { sortStandingRowsWithTiebreakers } from "@/lib/domain/kbo/tiebreakers";
import type { Game, KboSeasonRuleset, StandingRow, TeamSeasonStat } from "@/lib/domain/kbo/types";

describe("sortStandingRowsWithTiebreakers", () => {
  it("breaks identical pct ties with head-to-head results", () => {
    const ruleset: KboSeasonRuleset = {
      rulesetId: "test",
      label: "test",
      regularSeasonGamesPerTeam: 144,
      gamesPerOpponent: 16,
      tiesAllowed: true,
      tiebreakerOrder: ["headToHead", "runDifferential", "runScored", "teamCode"],
      specialPlayoffGamePositions: [],
      postseasonFormat: [],
      notes: [],
    };
    const rows: StandingRow[] = [
      {
        seasonTeamId: "season:a",
        brandId: "a",
        franchiseId: "a",
        teamSlug: "a",
        displayNameKo: "A",
        shortNameKo: "A",
        shortCode: "A",
        primaryColor: "#000",
        secondaryColor: "#fff",
        rank: 0,
        games: 4,
        wins: 2,
        losses: 2,
        ties: 0,
        pct: 0.5,
        gamesBack: 0,
        recent10: "-",
        streak: "-",
        home: "-",
        away: "-",
        runsScored: 12,
        runsAllowed: 12,
        offensePlus: 100,
        pitchingPlus: 100,
      },
      {
        seasonTeamId: "season:b",
        brandId: "b",
        franchiseId: "b",
        teamSlug: "b",
        displayNameKo: "B",
        shortNameKo: "B",
        shortCode: "B",
        primaryColor: "#000",
        secondaryColor: "#fff",
        rank: 0,
        games: 4,
        wins: 2,
        losses: 2,
        ties: 0,
        pct: 0.5,
        gamesBack: 0,
        recent10: "-",
        streak: "-",
        home: "-",
        away: "-",
        runsScored: 11,
        runsAllowed: 11,
        offensePlus: 100,
        pitchingPlus: 100,
      },
    ];
    const games: Game[] = [
      {
        gameId: "g1",
        seasonId: "season",
        seriesId: "s1",
        homeSeasonTeamId: "season:a",
        awaySeasonTeamId: "season:b",
        scheduledAt: "2026-04-01T18:30:00+09:00",
        status: "final",
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: 5,
        awayScore: 2,
        innings: 9,
        isTie: false,
        note: null,
        attendance: 0,
        externalLinks: [],
      },
      {
        gameId: "g2",
        seasonId: "season",
        seriesId: "s1",
        homeSeasonTeamId: "season:b",
        awaySeasonTeamId: "season:a",
        scheduledAt: "2026-04-02T18:30:00+09:00",
        status: "final",
        originalScheduledAt: null,
        rescheduledFromGameId: null,
        homeScore: 1,
        awayScore: 4,
        innings: 9,
        isTie: false,
        note: null,
        attendance: 0,
        externalLinks: [],
      },
    ];
    const stats: TeamSeasonStat[] = [
      {
        seasonId: "season",
        seasonTeamId: "season:a",
        wins: 2,
        losses: 2,
        ties: 0,
        runsScored: 12,
        runsAllowed: 12,
        homeWins: 1,
        homeLosses: 1,
        awayWins: 1,
        awayLosses: 1,
        last10: "-",
        streak: "-",
        offensePlus: 100,
        pitchingPlus: 100,
        bullpenEra: 4,
        teamWar: 0,
      },
      {
        seasonId: "season",
        seasonTeamId: "season:b",
        wins: 2,
        losses: 2,
        ties: 0,
        runsScored: 11,
        runsAllowed: 11,
        homeWins: 1,
        homeLosses: 1,
        awayWins: 1,
        awayLosses: 1,
        last10: "-",
        streak: "-",
        offensePlus: 100,
        pitchingPlus: 100,
        bullpenEra: 4,
        teamWar: 0,
      },
    ];

    const result = sortStandingRowsWithTiebreakers(rows, games, ruleset, stats);
    expect(result.rows[0].seasonTeamId).toBe("season:a");
  });
});
