import { describe, expect, it } from "vitest";

import { buildTrainingCorpusSeason } from "@/lib/data-sources/kbo/derive/build-training-corpus";

describe("training corpus builder", () => {
  it("builds team and game examples from history training seasons", () => {
    const corpus = buildTrainingCorpusSeason({
      generatedAt: "2026-04-17T00:00:00.000Z",
      seasonId: "kbo-2025",
      year: 2025,
      teamCount: 2,
      scheduledGameCount: 1,
      completedGameCount: 1,
      scheduleSnapshotCount: 1,
      scoreboardSnapshotCount: 1,
      historicalRecordSnapshotKey: "2026-04-17",
      teams: [
        {
          teamKey: "history-2025-lg",
          franchiseId: "lg",
          brandId: "lg-twins",
          brandLabel: "LG 트윈스",
          shortCode: "LG",
        },
        {
          teamKey: "history-2025-kia",
          franchiseId: "kia",
          brandId: "kia-tigers",
          brandLabel: "KIA 타이거즈",
          shortCode: "KIA",
        },
      ],
      gameLedger: [
        {
          gameKey: "20250322-kia-lg-14:00",
          date: "2025-03-22",
          scheduledAt: "2025-03-22T14:00:00+09:00",
          homeFranchiseId: "lg",
          awayFranchiseId: "kia",
          homeBrandLabel: "LG 트윈스",
          awayBrandLabel: "KIA 타이거즈",
          venueName: "잠실",
          status: "final",
          homeScore: 5,
          awayScore: 2,
          innings: 9,
          isTie: false,
          scheduleSeen: true,
          scoreboardSeen: true,
        },
      ],
      snapshots: [
        {
          asOfDate: "2025-03-21",
          completedGames: 0,
          remainingGames: 1,
          teams: [
            {
              teamKey: "history-2025-lg",
              franchiseId: "lg",
              brandId: "lg-twins",
              brandLabel: "LG 트윈스",
              shortCode: "LG",
              rank: 1,
              games: 0,
              wins: 0,
              losses: 0,
              ties: 0,
              pct: 0,
              gamesBack: 0,
              recent10: "0-0",
              streak: "-",
              runsScored: 0,
              runsAllowed: 0,
              runDifferential: 0,
              homeWins: 0,
              homeLosses: 0,
              homeTies: 0,
              awayWins: 0,
              awayLosses: 0,
              awayTies: 0,
              remainingGames: 1,
              remainingHomeGames: 1,
              remainingAwayGames: 0,
              remainingByOpponent: { kia: 1 },
              nextGameDate: "2025-03-22",
              nextOpponentFranchiseId: "kia",
              nextOpponentBrandLabel: "KIA 타이거즈",
              finalRank: 1,
              finalWins: 1,
              finalLosses: 0,
              finalTies: 0,
              winsRemainingToFinal: 1,
              lossesRemainingToFinal: 0,
              tiesRemainingToFinal: 0,
            },
            {
              teamKey: "history-2025-kia",
              franchiseId: "kia",
              brandId: "kia-tigers",
              brandLabel: "KIA 타이거즈",
              shortCode: "KIA",
              rank: 2,
              games: 0,
              wins: 0,
              losses: 0,
              ties: 0,
              pct: 0,
              gamesBack: 0,
              recent10: "0-0",
              streak: "-",
              runsScored: 0,
              runsAllowed: 0,
              runDifferential: 0,
              homeWins: 0,
              homeLosses: 0,
              homeTies: 0,
              awayWins: 0,
              awayLosses: 0,
              awayTies: 0,
              remainingGames: 1,
              remainingHomeGames: 0,
              remainingAwayGames: 1,
              remainingByOpponent: { lg: 1 },
              nextGameDate: "2025-03-22",
              nextOpponentFranchiseId: "lg",
              nextOpponentBrandLabel: "LG 트윈스",
              finalRank: 2,
              finalWins: 0,
              finalLosses: 1,
              finalTies: 0,
              winsRemainingToFinal: 0,
              lossesRemainingToFinal: 1,
              tiesRemainingToFinal: 0,
            },
          ],
        },
        {
          asOfDate: "2025-03-22",
          completedGames: 1,
          remainingGames: 0,
          teams: [
            {
              teamKey: "history-2025-lg",
              franchiseId: "lg",
              brandId: "lg-twins",
              brandLabel: "LG 트윈스",
              shortCode: "LG",
              rank: 1,
              games: 1,
              wins: 1,
              losses: 0,
              ties: 0,
              pct: 1,
              gamesBack: 0,
              recent10: "1-0",
              streak: "승1",
              runsScored: 5,
              runsAllowed: 2,
              runDifferential: 3,
              homeWins: 1,
              homeLosses: 0,
              homeTies: 0,
              awayWins: 0,
              awayLosses: 0,
              awayTies: 0,
              remainingGames: 0,
              remainingHomeGames: 0,
              remainingAwayGames: 0,
              remainingByOpponent: {},
              nextGameDate: null,
              nextOpponentFranchiseId: null,
              nextOpponentBrandLabel: null,
              finalRank: 1,
              finalWins: 1,
              finalLosses: 0,
              finalTies: 0,
              winsRemainingToFinal: 0,
              lossesRemainingToFinal: 0,
              tiesRemainingToFinal: 0,
            },
            {
              teamKey: "history-2025-kia",
              franchiseId: "kia",
              brandId: "kia-tigers",
              brandLabel: "KIA 타이거즈",
              shortCode: "KIA",
              rank: 2,
              games: 1,
              wins: 0,
              losses: 1,
              ties: 0,
              pct: 0,
              gamesBack: 1,
              recent10: "0-1",
              streak: "패1",
              runsScored: 2,
              runsAllowed: 5,
              runDifferential: -3,
              homeWins: 0,
              homeLosses: 0,
              homeTies: 0,
              awayWins: 0,
              awayLosses: 1,
              awayTies: 0,
              remainingGames: 0,
              remainingHomeGames: 0,
              remainingAwayGames: 0,
              remainingByOpponent: {},
              nextGameDate: null,
              nextOpponentFranchiseId: null,
              nextOpponentBrandLabel: null,
              finalRank: 2,
              finalWins: 0,
              finalLosses: 1,
              finalTies: 0,
              winsRemainingToFinal: 0,
              lossesRemainingToFinal: 0,
              tiesRemainingToFinal: 0,
            },
          ],
        },
      ],
    });

    expect(corpus.teamExampleCount).toBe(2);
    expect(corpus.gameExampleCount).toBe(1);
    expect(corpus.teamExamples[0]).toMatchObject({
      franchiseId: "lg",
      currentRank: 1,
      gamesRemaining: 1,
      finalChampion: true,
      winsRemaining: 1,
    });
    expect(corpus.teamExamples[0]?.derivedOffenseRating).toBeCloseTo(100, 4);
    expect(corpus.teamExamples[0]?.derivedStarterRating).toBeCloseTo(100, 4);
    expect(corpus.teamExamples[0]?.derivedBullpenRating).toBeCloseTo(100, 4);
    expect(corpus.teamExamples[0]?.derivedHomeFieldAdjustment).toBeCloseTo(0.18, 4);
    expect(corpus.teamExamples[0]?.derivedConfidenceScore).toBeGreaterThan(0.25);
    expect(corpus.gameExamples[0]).toMatchObject({
      date: "2025-03-22",
      homeFranchiseId: "lg",
      awayFranchiseId: "kia",
      outcome: "homeWin",
      homeWin: true,
      awayWin: false,
      homeRank: 1,
      awayRank: 2,
    });
    expect(corpus.gameExamples[0]?.homeDerivedOffenseRating).toBeCloseTo(100, 4);
    expect(corpus.gameExamples[0]?.awayDerivedOffenseRating).toBeCloseTo(100, 4);
    expect(corpus.gameExamples[0]?.homeDerivedHomeFieldAdjustment).toBeCloseTo(0.18, 4);
  });
});
