import type { KboDataBundle } from "@/lib/domain/kbo/types";
import type {
  DatasetId,
  FetchStrategy,
  ManualSourcePatchBundle,
  NormalizedDatasetFileName,
  NormalizedSourceReference,
  ParsedFranchiseHistoryRow,
  ParsedHistoricalTeamRecordRow,
  ParsedPlayerAwardRow,
  ParsedPlayerRegisterRow,
  ParsedRosterMovementRow,
  ParsedRulesetRow,
  ParsedScheduleRow,
  ParsedScoreboardRow,
  ParsedStandingsRow,
  ParsedTeamHitterStatRow,
  ParsedTeamPitcherStatRow,
  RawSourceSnapshot,
  SourceId,
  SourceTrustTier,
} from "@/lib/data-sources/kbo/dataset-types";
import { kboSourceFeatureFlags } from "@/lib/data-sources/kbo/dataset-types";
import { parseOfficialEnDailySchedule } from "@/lib/data-sources/kbo/adapters/official-en/daily-schedule";
import { parseOfficialEnBattingTop5 } from "@/lib/data-sources/kbo/adapters/official-en/batting-top5";
import { parseOfficialEnPitchingTop5 } from "@/lib/data-sources/kbo/adapters/official-en/pitching-top5";
import { parseOfficialEnPlayerGameLogsHitter } from "@/lib/data-sources/kbo/adapters/official-en/player-game-logs-hitter";
import { parseOfficialEnPlayerGameLogsPitcher } from "@/lib/data-sources/kbo/adapters/official-en/player-game-logs-pitcher";
import { parseOfficialEnPlayerSplitsMonthHitter } from "@/lib/data-sources/kbo/adapters/official-en/player-splits-month-hitter";
import { parseOfficialEnPlayerSplitsMonthPitcher } from "@/lib/data-sources/kbo/adapters/official-en/player-splits-month-pitcher";
import { parseOfficialEnPlayerSituationsHitter } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-hitter";
import { parseOfficialEnPlayerSituationsPitcher } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-pitcher";
import { parseOfficialEnPlayerSituationsCountHitter } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-count-hitter";
import { parseOfficialEnPlayerSituationsCountPitcher } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-count-pitcher";
import { parseOfficialEnPlayerSituationsRunnerHitter } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-runner-hitter";
import { parseOfficialEnPlayerSituationsRunnerPitcher } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-runner-pitcher";
import { parseOfficialEnPlayerSituationsOutHitter } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-out-hitter";
import { parseOfficialEnPlayerSituationsOutPitcher } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-out-pitcher";
import { parseOfficialEnPlayerSituationsInningHitter } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-inning-hitter";
import { parseOfficialEnPlayerSituationsInningPitcher } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-inning-pitcher";
import { parseOfficialEnPlayerSituationsBattingOrderHitter } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-batting-order-hitter";
import { parseOfficialEnPlayerSituationsBattingOrderPitcher } from "@/lib/data-sources/kbo/adapters/official-en/player-situations-batting-order-pitcher";
import { parseOfficialEnScoreboard } from "@/lib/data-sources/kbo/adapters/official-en/scoreboard";
import { parseOfficialEnStandings } from "@/lib/data-sources/kbo/adapters/official-en/standings";
import { parseOfficialEnPlayerSearch } from "@/lib/data-sources/kbo/adapters/official-en/player-search";
import { parseOfficialEnTeamInformation } from "@/lib/data-sources/kbo/adapters/official-en/team-information";
import { parseOfficialKoHistoricalTeamRecord } from "@/lib/data-sources/kbo/adapters/official-ko/historical-team-record";
import { parseOfficialKoPlayerAwardsDefensePrize } from "@/lib/data-sources/kbo/adapters/official-ko/player-awards-defense-prize";
import { parseOfficialKoPlayerAwardsGoldenGlove } from "@/lib/data-sources/kbo/adapters/official-ko/player-awards-golden-glove";
import { parseOfficialKoPlayerAwardsMvpRookie } from "@/lib/data-sources/kbo/adapters/official-ko/player-awards-mvp-rookie";
import { parseOfficialKoPlayerAwardsSeriesPrize } from "@/lib/data-sources/kbo/adapters/official-ko/player-awards-series-prize";
import { parseOfficialKoRegister } from "@/lib/data-sources/kbo/adapters/official-ko/register";
import { parseOfficialKoRegisterAll } from "@/lib/data-sources/kbo/adapters/official-ko/register-all";
import { parseOfficialKoRules } from "@/lib/data-sources/kbo/adapters/official-ko/rules";
import { parseOfficialKoSchedule } from "@/lib/data-sources/kbo/adapters/official-ko/schedule";
import { parseOfficialKoScoreboard } from "@/lib/data-sources/kbo/adapters/official-ko/scoreboard";
import { parseOfficialKoStandings } from "@/lib/data-sources/kbo/adapters/official-ko/standings";
import { parseOfficialKoTeamHitter } from "@/lib/data-sources/kbo/adapters/official-ko/team-hitter";
import { parseOfficialKoTeamHistory } from "@/lib/data-sources/kbo/adapters/official-ko/team-history";
import { parseOfficialKoTeamPitcher } from "@/lib/data-sources/kbo/adapters/official-ko/team-pitcher";
import { parseOfficialKoTrade } from "@/lib/data-sources/kbo/adapters/official-ko/trade";
import { parseOfficialKoWeather } from "@/lib/data-sources/kbo/adapters/official-ko/weather";
import { parseStatizPlayerStats } from "@/lib/data-sources/kbo/adapters/statiz/player-stats";
import { parseStatizTeamStats } from "@/lib/data-sources/kbo/adapters/statiz/team-stats";
import { parseStatizWar } from "@/lib/data-sources/kbo/adapters/statiz/war";
import { normalizeFranchiseHistory } from "@/lib/data-sources/kbo/normalize/franchise-history";
import { normalizeAwards } from "@/lib/data-sources/kbo/normalize/awards";
import { normalizeHistoricalTeamRecord } from "@/lib/data-sources/kbo/normalize/historical-team-record";
import { normalizePlayerDirectory } from "@/lib/data-sources/kbo/normalize/player-directory";
import { normalizeRosterEvents } from "@/lib/data-sources/kbo/normalize/roster-events";
import { normalizeRulesets } from "@/lib/data-sources/kbo/normalize/ruleset";
import { normalizeScheduleToSeriesGames } from "@/lib/data-sources/kbo/normalize/schedule-to-series-games";
import { normalizeScoreboard } from "@/lib/data-sources/kbo/normalize/scoreboard";
import { normalizeStandings } from "@/lib/data-sources/kbo/normalize/standings";
import { normalizeTeamHitterStats, normalizeTeamPitcherStats } from "@/lib/data-sources/kbo/normalize/team-stats";

export type SourceRegistryEntry<TDataset extends DatasetId = DatasetId> = {
  sourceId: SourceId;
  datasetId: TDataset;
  priority: number;
  required: boolean;
  enabled: boolean;
  trustTier: SourceTrustTier;
  sourceUrl: string;
  fetchStrategy: FetchStrategy;
  cacheTtlMs: number;
  legalNote: string;
  parserVersion: string;
  fixturePath: string | null;
  normalizedTarget: NormalizedDatasetFileName | null;
  parser: (html: string) => unknown;
  normalizer:
    | null
    | ((args: {
        seasonId: string;
        parsed: unknown;
        bundle: KboDataBundle;
        patches: ManualSourcePatchBundle;
        sourceRef: NormalizedSourceReference;
      }) => unknown);
};

const OFFICIAL_KBO_LEGAL_NOTE = "Official KBO HTML snapshots are baseline truth candidates. Store HTML and metadata, not copyrighted media assets.";
const STATIZ_LEGAL_NOTE = "Statiz is optional enrichment only. Do not use as baseline truth for standings, schedule, or results.";

export const kboSourceRegistry: SourceRegistryEntry[] = [
  {
    sourceId: "official-kbo-en",
    datasetId: "schedule-calendar",
    priority: 2,
    required: true,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Schedule/DailySchedule.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 20,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-schedule-v2",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/daily-schedule.html",
    normalizedTarget: "series-games",
    parser: parseOfficialEnDailySchedule,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeScheduleToSeriesGames({
        seasonId,
        sourceId: "official-kbo-en",
        rows: parsed as ParsedScheduleRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "schedule-calendar",
    priority: 1,
    required: true,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/schedule/schedule.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 20,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-schedule-v2",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/schedule.html",
    normalizedTarget: "series-games",
    parser: parseOfficialKoSchedule,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeScheduleToSeriesGames({
        seasonId,
        sourceId: "official-kbo-ko",
        rows: parsed as ParsedScheduleRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "scoreboard",
    priority: 1,
    required: true,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Schedule/Scoreboard.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 5,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-scoreboard-v2",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/scoreboard.html",
    normalizedTarget: "scoreboard",
    parser: parseOfficialEnScoreboard,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeScoreboard({
        seasonId,
        sourceId: "official-kbo-en",
        rows: parsed as ParsedScoreboardRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "scoreboard",
    priority: 2,
    required: true,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/schedule/scoreboard.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 5,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-scoreboard-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/scoreboard.html",
    normalizedTarget: "scoreboard",
    parser: parseOfficialKoScoreboard,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeScoreboard({
        seasonId,
        sourceId: "official-kbo-ko",
        rows: parsed as ParsedScoreboardRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "standings",
    priority: 1,
    required: true,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Standings/TeamStandings.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 20,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-standings-v2",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/standings.html",
    normalizedTarget: "standings",
    parser: parseOfficialEnStandings,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeStandings({
        seasonId,
        sourceId: "official-kbo-en",
        rows: parsed as ParsedStandingsRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "standings",
    priority: 2,
    required: true,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/record/teamrank/teamrank.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 20,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-standings-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/standings.html",
    normalizedTarget: "standings",
    parser: parseOfficialKoStandings,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeStandings({
        seasonId,
        sourceId: "official-kbo-ko",
        rows: parsed as ParsedStandingsRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "batting-top5",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/stats/BattingTop5.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 6,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-batting-top5-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/batting-top5.html",
    normalizedTarget: null,
    parser: parseOfficialEnBattingTop5,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "pitching-top5",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/stats/PitchingTop5.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 6,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-pitching-top5-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/pitching-top5.html",
    normalizedTarget: null,
    parser: parseOfficialEnPitchingTop5,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-game-logs-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoHitter/GameLogs.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 6,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-game-logs-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-game-logs-hitter-53123.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerGameLogsHitter,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-game-logs-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoPitcher/GameLogs.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 6,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-game-logs-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-game-logs-pitcher-61101.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerGameLogsPitcher,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-splits-month-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoHitter/SplitsMonth.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-splits-month-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-splits-month-hitter-53123.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSplitsMonthHitter,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-splits-month-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoPitcher/SplitsMonth.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-splits-month-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-splits-month-pitcher-61101.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSplitsMonthPitcher,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoHitter/SituationsPitcher.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-hitter-53123.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsHitter,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoPitcher/SituationsBatter.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-pitcher-61101.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsPitcher,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-count-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoHitter/SituationsCount.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-count-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-count-hitter-53123.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsCountHitter,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-count-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoPitcher/SituationsCount.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-count-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-count-pitcher-61101.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsCountPitcher,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-runner-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoHitter/SituationsRunner.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-runner-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-runner-hitter-53123.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsRunnerHitter,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-runner-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoPitcher/SituationsRunner.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-runner-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-runner-pitcher-61101.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsRunnerPitcher,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-out-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoHitter/SituationsOut.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-out-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-out-hitter-53123.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsOutHitter,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-out-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoPitcher/SituationsOut.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-out-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-out-pitcher-61101.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsOutPitcher,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-inning-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoHitter/SituationsInning.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-inning-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-inning-hitter-53123.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsInningHitter,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-inning-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoPitcher/SituationsInning.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-inning-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-inning-pitcher-61101.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsInningPitcher,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-batting-order-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoHitter/SituationsBattingOrder.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-batting-order-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-batting-order-hitter-53123.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsBattingOrderHitter,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-situations-batting-order-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerInfoPitcher/SituationsBattingOrder.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-situations-batting-order-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-en/player-situations-batting-order-pitcher-61101.html",
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSituationsBattingOrderPitcher,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "player-awards-mvp-rookie",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Player/Awards/PlayerPrize.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 24,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-18-ko-player-awards-mvp-rookie-v1",
    fixturePath: null,
    normalizedTarget: "awards",
    parser: parseOfficialKoPlayerAwardsMvpRookie,
    normalizer: ({ parsed, bundle, patches, sourceRef }) =>
      normalizeAwards({
        rows: parsed as ParsedPlayerAwardRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "player-awards-golden-glove",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Player/Awards/GoldenGlove.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 24,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-18-ko-player-awards-golden-glove-v1",
    fixturePath: null,
    normalizedTarget: "awards",
    parser: parseOfficialKoPlayerAwardsGoldenGlove,
    normalizer: ({ parsed, bundle, patches, sourceRef }) =>
      normalizeAwards({
        rows: parsed as ParsedPlayerAwardRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "player-awards-defense-prize",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Player/Awards/DefensePrize.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 24,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-18-ko-player-awards-defense-prize-v1",
    fixturePath: null,
    normalizedTarget: "awards",
    parser: parseOfficialKoPlayerAwardsDefensePrize,
    normalizer: ({ parsed, bundle, patches, sourceRef }) =>
      normalizeAwards({
        rows: parsed as ParsedPlayerAwardRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "player-awards-series-prize",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Player/Awards/SeriesPrize.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 24,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-18-ko-player-awards-series-prize-v1",
    fixturePath: null,
    normalizedTarget: "awards",
    parser: parseOfficialKoPlayerAwardsSeriesPrize,
    normalizer: ({ parsed, bundle, patches, sourceRef }) =>
      normalizeAwards({
        rows: parsed as ParsedPlayerAwardRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "player-register",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/player/register.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-register-v1",
    fixturePath: null,
    normalizedTarget: null,
    parser: parseOfficialKoRegister,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "player-register-all",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Player/RegisterAll.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-register-all-v2",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/register-all.html",
    normalizedTarget: "players",
    parser: parseOfficialKoRegisterAll,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizePlayerDirectory({
        seasonId,
        sourceId: "official-kbo-ko",
        rows: parsed as ParsedPlayerRegisterRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "roster-movement",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/player/trade.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 6,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-trade-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/trade.html",
    normalizedTarget: "roster-events",
    parser: parseOfficialKoTrade,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeRosterEvents({
        seasonId,
        sourceId: "official-kbo-ko",
        rows: parsed as ParsedRosterMovementRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "historical-team-record",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Record/History/Team/Record.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 24,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-history-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/historical-team-record-live.html",
    normalizedTarget: "historical-team-records",
    parser: parseOfficialKoHistoricalTeamRecord,
    normalizer: ({ parsed, bundle, patches, sourceRef }) =>
      normalizeHistoricalTeamRecord({
        rows: parsed as ParsedHistoricalTeamRecordRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "team-history",
    priority: 1,
    required: true,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/kbo/league/teamhistory.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 24,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-team-history-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/team-history.html",
    normalizedTarget: "franchise-lineage",
    parser: parseOfficialKoTeamHistory,
    normalizer: ({ parsed, bundle, patches, sourceRef }) =>
      normalizeFranchiseHistory({
        rows: parsed as ParsedFranchiseHistoryRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "team-hitter",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Record/Team/Hitter/Basic1.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 6,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-team-hitter-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/team-hitter.html",
    normalizedTarget: "team-hitter-stats",
    parser: parseOfficialKoTeamHitter,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeTeamHitterStats({
        seasonId,
        sourceId: "official-kbo-ko",
        rows: parsed as ParsedTeamHitterStatRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "team-pitcher",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Record/Team/Pitcher/BasicOld.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 6,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-team-pitcher-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/team-pitcher.html",
    normalizedTarget: "team-pitcher-stats",
    parser: parseOfficialKoTeamPitcher,
    normalizer: ({ seasonId, parsed, bundle, patches, sourceRef }) =>
      normalizeTeamPitcherStats({
        seasonId,
        sourceId: "official-kbo-ko",
        rows: parsed as ParsedTeamPitcherStatRow[],
        bundle,
        patches,
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "rules",
    priority: 1,
    required: true,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/Kbo/League/GameManage2026.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 24,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-rules-v1",
    fixturePath: "src/lib/data-sources/kbo/fixtures/official-ko/rules.html",
    normalizedTarget: "rulesets",
    parser: parseOfficialKoRules,
    normalizer: ({ parsed, sourceRef }) =>
      normalizeRulesets({
        rows: parsed as ParsedRulesetRow[],
        sourceRef,
      }),
  },
  {
    sourceId: "official-kbo-ko",
    datasetId: "weather",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-baseline",
    sourceUrl: "https://www.koreabaseball.com/schedule/weather.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-ko-weather-v1",
    fixturePath: null,
    normalizedTarget: null,
    parser: parseOfficialKoWeather,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "player-search",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/PlayerSearch.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-player-search-v1",
    fixturePath: null,
    normalizedTarget: null,
    parser: parseOfficialEnPlayerSearch,
    normalizer: null,
  },
  {
    sourceId: "official-kbo-en",
    datasetId: "team-information",
    priority: 1,
    required: false,
    enabled: true,
    trustTier: "official-mirror",
    sourceUrl: "https://eng.koreabaseball.com/Teams/TeamInformation.aspx",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 24,
    legalNote: OFFICIAL_KBO_LEGAL_NOTE,
    parserVersion: "2026-04-15-en-team-information-v1",
    fixturePath: null,
    normalizedTarget: null,
    parser: parseOfficialEnTeamInformation,
    normalizer: null,
  },
  {
    sourceId: "statiz",
    datasetId: "statiz-team-stats",
    priority: 1,
    required: false,
    enabled: !kboSourceFeatureFlags.officialKboOnly && kboSourceFeatureFlags.enableStatizEnrichment,
    trustTier: "optional-enrichment",
    sourceUrl: "https://www.statiz.co.kr/",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: STATIZ_LEGAL_NOTE,
    parserVersion: "2026-04-15-statiz-team-stats-v1",
    fixturePath: null,
    normalizedTarget: null,
    parser: parseStatizTeamStats,
    normalizer: null,
  },
  {
    sourceId: "statiz",
    datasetId: "statiz-player-stats",
    priority: 1,
    required: false,
    enabled: !kboSourceFeatureFlags.officialKboOnly && kboSourceFeatureFlags.enableStatizEnrichment,
    trustTier: "optional-enrichment",
    sourceUrl: "https://www.statiz.co.kr/",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: STATIZ_LEGAL_NOTE,
    parserVersion: "2026-04-15-statiz-player-stats-v1",
    fixturePath: null,
    normalizedTarget: null,
    parser: parseStatizPlayerStats,
    normalizer: null,
  },
  {
    sourceId: "statiz",
    datasetId: "statiz-war",
    priority: 1,
    required: false,
    enabled: !kboSourceFeatureFlags.officialKboOnly && kboSourceFeatureFlags.enableStatizEnrichment,
    trustTier: "optional-enrichment",
    sourceUrl: "https://www.statiz.co.kr/",
    fetchStrategy: "html",
    cacheTtlMs: 1000 * 60 * 60 * 12,
    legalNote: STATIZ_LEGAL_NOTE,
    parserVersion: "2026-04-15-statiz-war-v1",
    fixturePath: null,
    normalizedTarget: null,
    parser: parseStatizWar,
    normalizer: null,
  },
];

export function getRegistryEntriesForDataset(datasetId: DatasetId) {
  return kboSourceRegistry.filter((entry) => entry.datasetId === datasetId);
}

export function getRegistryEntry(sourceId: SourceId, datasetId: DatasetId) {
  return kboSourceRegistry.find((entry) => entry.sourceId === sourceId && entry.datasetId === datasetId) ?? null;
}
