import { z } from "zod";

export const teamSnapshotTrainingExampleSchema = z.object({
  sampleId: z.string(),
  seasonId: z.string(),
  year: z.number().int(),
  asOfDate: z.string(),
  snapshotIndex: z.number().int().positive(),
  franchiseId: z.string(),
  brandId: z.string().nullable(),
  brandLabel: z.string(),
  shortCode: z.string(),
  currentRank: z.number().int().positive(),
  currentTop3: z.boolean(),
  currentTop5: z.boolean(),
  gamesPlayed: z.number().int().nonnegative(),
  gamesRemaining: z.number().int().nonnegative(),
  seasonProgress: z.number(),
  wins: z.number().int().nonnegative(),
  losses: z.number().int().nonnegative(),
  ties: z.number().int().nonnegative(),
  pct: z.number(),
  gamesBack: z.number(),
  recent10Wins: z.number().int().nonnegative(),
  recent10Losses: z.number().int().nonnegative(),
  recent10Ties: z.number().int().nonnegative(),
  recent10WinRate: z.number(),
  streakDirection: z.number().int(),
  streakLength: z.number().int().nonnegative(),
  streakValue: z.number().int(),
  runsScoredPerGame: z.number(),
  runsAllowedPerGame: z.number(),
  runDiffPerGame: z.number(),
  homePct: z.number(),
  awayPct: z.number(),
  splitPctGap: z.number(),
  remainingHomeShare: z.number(),
  remainingAwayShare: z.number(),
  remainingOpponentAvgPct: z.number(),
  remainingOpponentAvgGamesBack: z.number(),
  remainingOpponentAvgRunDiffPerGame: z.number(),
  remainingVsTop3: z.number().int().nonnegative(),
  remainingVsTop5: z.number().int().nonnegative(),
  remainingVsBottom3: z.number().int().nonnegative(),
  remainingVsWinningTeams: z.number().int().nonnegative(),
  derivedCurrentWeight: z.number(),
  derivedOffenseSignal: z.number(),
  derivedRunPreventionSignal: z.number(),
  derivedBullpenSignal: z.number(),
  derivedOffenseRating: z.number(),
  derivedStarterRating: z.number(),
  derivedBullpenRating: z.number(),
  derivedConfidenceScore: z.number(),
  derivedHomeFieldAdjustment: z.number(),
  derivedRecentFormAdjustment: z.number(),
  derivedScheduleDifficulty: z.number(),
  finalRank: z.number().int().positive(),
  finalWins: z.number().int().nonnegative(),
  finalLosses: z.number().int().nonnegative(),
  finalTies: z.number().int().nonnegative(),
  finalTop3: z.boolean(),
  finalTop5: z.boolean(),
  finalChampion: z.boolean(),
  winsRemaining: z.number().int(),
  lossesRemaining: z.number().int(),
  tiesRemaining: z.number().int(),
  rankDeltaToFinal: z.number().int(),
});
export type TeamSnapshotTrainingExample = z.infer<typeof teamSnapshotTrainingExampleSchema>;

export const gameOutcomeTrainingExampleSchema = z.object({
  sampleId: z.string(),
  seasonId: z.string(),
  year: z.number().int(),
  gameKey: z.string(),
  date: z.string(),
  scheduledAt: z.string(),
  month: z.number().int().min(1).max(12),
  homeFranchiseId: z.string(),
  awayFranchiseId: z.string(),
  homeBrandLabel: z.string(),
  awayBrandLabel: z.string(),
  homeRank: z.number().int().positive(),
  awayRank: z.number().int().positive(),
  rankGap: z.number().int(),
  homePct: z.number(),
  awayPct: z.number(),
  pctGap: z.number(),
  homeGamesBack: z.number(),
  awayGamesBack: z.number(),
  gamesBackGap: z.number(),
  homeRecent10WinRate: z.number(),
  awayRecent10WinRate: z.number(),
  recent10Gap: z.number(),
  homeRunsScoredPerGame: z.number(),
  awayRunsScoredPerGame: z.number(),
  offenseGap: z.number(),
  homeRunsAllowedPerGame: z.number(),
  awayRunsAllowedPerGame: z.number(),
  defenseGap: z.number(),
  homeRunDiffPerGame: z.number(),
  awayRunDiffPerGame: z.number(),
  runDiffGap: z.number(),
  homeHomePct: z.number(),
  awayAwayPct: z.number(),
  venueSplitGap: z.number(),
  homeSeasonProgress: z.number(),
  awaySeasonProgress: z.number(),
  progressGap: z.number(),
  homeDerivedCurrentWeight: z.number(),
  awayDerivedCurrentWeight: z.number(),
  currentWeightGap: z.number(),
  homeDerivedOffenseRating: z.number(),
  awayDerivedOffenseRating: z.number(),
  offenseRatingGap: z.number(),
  homeDerivedStarterRating: z.number(),
  awayDerivedStarterRating: z.number(),
  starterRatingGap: z.number(),
  homeDerivedBullpenRating: z.number(),
  awayDerivedBullpenRating: z.number(),
  bullpenRatingGap: z.number(),
  homeDerivedConfidenceScore: z.number(),
  awayDerivedConfidenceScore: z.number(),
  confidenceScoreGap: z.number(),
  homeDerivedRecentFormAdjustment: z.number(),
  awayDerivedRecentFormAdjustment: z.number(),
  recentFormAdjustmentGap: z.number(),
  homeDerivedScheduleDifficulty: z.number(),
  awayDerivedScheduleDifficulty: z.number(),
  scheduleDifficultyGap: z.number(),
  homeDerivedHomeFieldAdjustment: z.number(),
  homeRestDays: z.number().int().nullable(),
  awayRestDays: z.number().int().nullable(),
  restGap: z.number().int().nullable(),
  outcome: z.enum(["homeWin", "awayWin", "tie"]),
  homeWin: z.boolean(),
  awayWin: z.boolean(),
  tie: z.boolean(),
  homeScore: z.number().int(),
  awayScore: z.number().int(),
});
export type GameOutcomeTrainingExample = z.infer<typeof gameOutcomeTrainingExampleSchema>;

export const trainingCorpusSeasonSchema = z.object({
  generatedAt: z.string(),
  seasonId: z.string(),
  year: z.number().int(),
  teamExampleCount: z.number().int().nonnegative(),
  gameExampleCount: z.number().int().nonnegative(),
  teamExamples: z.array(teamSnapshotTrainingExampleSchema),
  gameExamples: z.array(gameOutcomeTrainingExampleSchema),
});
export type TrainingCorpusSeason = z.infer<typeof trainingCorpusSeasonSchema>;

export const trainingCorpusBundleSchema = z.object({
  generatedAt: z.string(),
  years: z.array(z.number().int()),
  teamExampleCount: z.number().int().nonnegative(),
  gameExampleCount: z.number().int().nonnegative(),
  teamExamples: z.array(teamSnapshotTrainingExampleSchema),
  gameExamples: z.array(gameOutcomeTrainingExampleSchema),
});
export type TrainingCorpusBundle = z.infer<typeof trainingCorpusBundleSchema>;
